/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhoneNumberRouteImport } from './routes/$phoneNumber'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BGTillNumberRouteImport } from './routes/BG.$tillNumber'
import { Route as PBPaybillAccountNumberRouteImport } from './routes/PB.$paybill.$accountNumber'

const PhoneNumberRoute = PhoneNumberRouteImport.update({
  id: '/$phoneNumber',
  path: '/$phoneNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BGTillNumberRoute = BGTillNumberRouteImport.update({
  id: '/BG/$tillNumber',
  path: '/BG/$tillNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const PBPaybillAccountNumberRoute = PBPaybillAccountNumberRouteImport.update({
  id: '/PB/$paybill/$accountNumber',
  path: '/PB/$paybill/$accountNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$phoneNumber': typeof PhoneNumberRoute
  '/BG/$tillNumber': typeof BGTillNumberRoute
  '/PB/$paybill/$accountNumber': typeof PBPaybillAccountNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$phoneNumber': typeof PhoneNumberRoute
  '/BG/$tillNumber': typeof BGTillNumberRoute
  '/PB/$paybill/$accountNumber': typeof PBPaybillAccountNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$phoneNumber': typeof PhoneNumberRoute
  '/BG/$tillNumber': typeof BGTillNumberRoute
  '/PB/$paybill/$accountNumber': typeof PBPaybillAccountNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$phoneNumber'
    | '/BG/$tillNumber'
    | '/PB/$paybill/$accountNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$phoneNumber' | '/BG/$tillNumber' | '/PB/$paybill/$accountNumber'
  id:
    | '__root__'
    | '/'
    | '/$phoneNumber'
    | '/BG/$tillNumber'
    | '/PB/$paybill/$accountNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhoneNumberRoute: typeof PhoneNumberRoute
  BGTillNumberRoute: typeof BGTillNumberRoute
  PBPaybillAccountNumberRoute: typeof PBPaybillAccountNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$phoneNumber': {
      id: '/$phoneNumber'
      path: '/$phoneNumber'
      fullPath: '/$phoneNumber'
      preLoaderRoute: typeof PhoneNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/BG/$tillNumber': {
      id: '/BG/$tillNumber'
      path: '/BG/$tillNumber'
      fullPath: '/BG/$tillNumber'
      preLoaderRoute: typeof BGTillNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PB/$paybill/$accountNumber': {
      id: '/PB/$paybill/$accountNumber'
      path: '/PB/$paybill/$accountNumber'
      fullPath: '/PB/$paybill/$accountNumber'
      preLoaderRoute: typeof PBPaybillAccountNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhoneNumberRoute: PhoneNumberRoute,
  BGTillNumberRoute: BGTillNumberRoute,
  PBPaybillAccountNumberRoute: PBPaybillAccountNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
