/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PhoneNumberImport } from './routes/$phoneNumber'
import { Route as IndexImport } from './routes/index'
import { Route as BGTillNumberImport } from './routes/BG.$tillNumber'
import { Route as PBPaybillAccountNumberImport } from './routes/PB.$paybill.$accountNumber'

// Create/Update Routes

const PhoneNumberRoute = PhoneNumberImport.update({
  id: '/$phoneNumber',
  path: '/$phoneNumber',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BGTillNumberRoute = BGTillNumberImport.update({
  id: '/BG/$tillNumber',
  path: '/BG/$tillNumber',
  getParentRoute: () => rootRoute,
} as any)

const PBPaybillAccountNumberRoute = PBPaybillAccountNumberImport.update({
  id: '/PB/$paybill/$accountNumber',
  path: '/PB/$paybill/$accountNumber',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$phoneNumber': {
      id: '/$phoneNumber'
      path: '/$phoneNumber'
      fullPath: '/$phoneNumber'
      preLoaderRoute: typeof PhoneNumberImport
      parentRoute: typeof rootRoute
    }
    '/BG/$tillNumber': {
      id: '/BG/$tillNumber'
      path: '/BG/$tillNumber'
      fullPath: '/BG/$tillNumber'
      preLoaderRoute: typeof BGTillNumberImport
      parentRoute: typeof rootRoute
    }
    '/PB/$paybill/$accountNumber': {
      id: '/PB/$paybill/$accountNumber'
      path: '/PB/$paybill/$accountNumber'
      fullPath: '/PB/$paybill/$accountNumber'
      preLoaderRoute: typeof PBPaybillAccountNumberImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$phoneNumber': typeof PhoneNumberRoute
  '/BG/$tillNumber': typeof BGTillNumberRoute
  '/PB/$paybill/$accountNumber': typeof PBPaybillAccountNumberRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$phoneNumber': typeof PhoneNumberRoute
  '/BG/$tillNumber': typeof BGTillNumberRoute
  '/PB/$paybill/$accountNumber': typeof PBPaybillAccountNumberRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$phoneNumber': typeof PhoneNumberRoute
  '/BG/$tillNumber': typeof BGTillNumberRoute
  '/PB/$paybill/$accountNumber': typeof PBPaybillAccountNumberRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$phoneNumber'
    | '/BG/$tillNumber'
    | '/PB/$paybill/$accountNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$phoneNumber' | '/BG/$tillNumber' | '/PB/$paybill/$accountNumber'
  id:
    | '__root__'
    | '/'
    | '/$phoneNumber'
    | '/BG/$tillNumber'
    | '/PB/$paybill/$accountNumber'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhoneNumberRoute: typeof PhoneNumberRoute
  BGTillNumberRoute: typeof BGTillNumberRoute
  PBPaybillAccountNumberRoute: typeof PBPaybillAccountNumberRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhoneNumberRoute: PhoneNumberRoute,
  BGTillNumberRoute: BGTillNumberRoute,
  PBPaybillAccountNumberRoute: PBPaybillAccountNumberRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$phoneNumber",
        "/BG/$tillNumber",
        "/PB/$paybill/$accountNumber"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$phoneNumber": {
      "filePath": "$phoneNumber.tsx"
    },
    "/BG/$tillNumber": {
      "filePath": "BG.$tillNumber.tsx"
    },
    "/PB/$paybill/$accountNumber": {
      "filePath": "PB.$paybill.$accountNumber.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
